### ISSUE TITLE
Repolinter fails with fatal error

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/repolinter-action#17]
## Description

The Ruby agent received a fatal error when the Repolinter action recently ran on merge: https://github.com/newrelic/newrelic-ruby-agent/actions/runs/5205539590/jobs/9391737988 

Are there any changes we need to make?

## Expected Behavior

Expect the repolinter action to run without a fatal error

## Relevant Logs / Console output

```
Error: A fatal error was thrown.
Error: Error: Creating an issue returned status 403. This is probably due to a scope limitation of your PAT, check that you set the correct permissions (note that GITHUB_TOKEN cannot write repositories other than it's own)
    at result (/repolinter-action/webpack:/repolinter-action/lib/createorUpdateIssue.js:224:1)
    at Generator.throw (<anonymous>)
    at rejected (/repolinter-action/webpack:/repolinter-action/lib/createorUpdateIssue.js:26:1)
```

## Your Environment

GitHub Actions
Workflow file describing the action: https://github.com/newrelic/newrelic-ruby-agent/blob/dev/.github/workflows/repolinter.yml

**Comment by kaylareopelle** [comment]
This isn't happening anymore
